### ISSUE TITLE
Error raised if preview glyph is missing in font

### ISSUE THREAD

**Issue by ryanbugden** [Typefounding/underlineStrikethrough#17]
I can get to this eventually.

```
Traceback (most recent call last):
  File "lib/doodleDelegate.pyc", line 87, in sendEvent_
  File "/Applications/RoboFont-4_4b2.app/Contents/Resources/lib/python3.9/vanilla/vanillaList2.py", line 224, in tableViewSelectionDidChange_
  File "Underline StrikeThrough.py", line 381, in tableSelectionCallback
  File "Underline StrikeThrough.py", line 517, in updatePreview
  File "lib/fontObjects/fontPartsWrappers.pyc", line 1865, in __getitem__
KeyError: "No glyph named 'm'."
```

**Comment by colinmford** [comment]
@ryanbugden @benkiel 

#22 fixes this

**Comment by ryanbugden** [comment]
Thanks @colinmford
