### ISSUE TITLE
TextField should use mojo.UI.splitText — Tracebacks when working with All Caps (or incomplete fonts)

### ISSUE THREAD

**Issue by colinmford** [Typefounding/underlineStrikethrough#21]
I've got a font where all the lowercase unicodes are mapped to the uppercase form, i.e. the glyph `/L` has unicodes 004C and 006C.

Opening this extension, I get 
```
Traceback (most recent call last):
  File "/Applications/RoboFont.app/Contents/Resources/lib/python3.9/vanilla/vanillaList2.py", line 227, in tableViewSelectionDidChange_
  File "Underline StrikeThrough.py", line 381, in tableSelectionCallback
  File "Underline StrikeThrough.py", line 517, in updatePreview
  File "lib/fontObjects/fontPartsWrappers.pyc", line 1866, in __getitem__
KeyError: "No glyph named 'l'."
Traceback (most recent call last):
  File "Underline StrikeThrough.py", line 570, in <module>
  File "/Applications/RoboFont.app/Contents/Resources/lib/python3.9/mojo/subscriber.py", line 3803, in registerRoboFontSubscriber
  File "/Applications/RoboFont.app/Contents/Resources/lib/python3.9/mojo/subscriber.py", line 3482, in addRoboFontSubscriber
  File "/Applications/RoboFont.app/Contents/Resources/lib/python3.9/mojo/subscriber.py", line 1461, in __init__
  File "Underline StrikeThrough.py", line 223, in started
  File "Underline StrikeThrough.py", line 344, in updateFontList
  File "/Applications/RoboFont.app/Contents/Resources/lib/python3.9/vanilla/vanillaList2.py", line 852, in setSelectedIndexes
  File "/Applications/RoboFont.app/Contents/Resources/lib/python3.9/vanilla/vanillaList2.py", line 227, in tableViewSelectionDidChange_
  File "Underline StrikeThrough.py", line 381, in tableSelectionCallback
  File "Underline StrikeThrough.py", line 517, in updatePreview
  File "lib/fontObjects/fontPartsWrappers.pyc", line 1866, in __getitem__
KeyError: "No glyph named 'l'."
```
It seems the textfield is just taking straight glyph names, as using a /s/l/a/s/h/e/d string also does not work. The solution to this would be to use the mojo.UI `splitText` method: https://robofont.com/documentation/reference/api/mojo/mojo-ui/#mojo.UI.splitText

**Comment by colinmford** [comment]
Oh, I guess this a dupe of #17
