### ISSUE TITLE
Traceback when selection of font changes in vanilla list

### ISSUE THREAD

**Issue by luke-snider** [Typefounding/underlineStrikethrough#5]
When I change the selection  in the vanilla list I get this traceback below and only the current  font is displayed - the preview doesn't change ;(

Traceback (most recent call last):
  File "/Applications/RoboFont.app/Contents/Resources/lib/python2.7/vanilla/vanillaList.py", line 46, in observeValueForKeyPath_ofObject_change_context_
    self._targetMethod()
  File "/Applications/RoboFont.app/Contents/Resources/lib/python2.7/vanilla/vanillaList.py", line 727, in _selection
    self._selectionCallback(self)
  File "Underline StrikeThrough.py", line 39, in updateSelectedFonts
  File "Underline StrikeThrough.py", line 138, in updateFont
  File "Underline StrikeThrough.py", line 113, in setUI
AttributeError: 'int' object has no attribute 'path'
Traceback (most recent call last):
  File "lib/doodleDelegate.pyc", line 169, in sendEvent_
  File "/Applications/RoboFont.app/Contents/Resources/lib/python2.7/vanilla/vanillaList.py", line 46, in observeValueForKeyPath_ofObject_change_context_
    self._targetMethod()
  File "/Applications/RoboFont.app/Contents/Resources/lib/python2.7/vanilla/vanillaList.py", line 727, in _selection
    self._selectionCallback(self)
  File "Underline StrikeThrough.py", line 39, in updateSelectedFonts
  File "Underline StrikeThrough.py", line 138, in updateFont
  File "Underline StrikeThrough.py", line 113, in setUI
AttributeError: 'int' object has no attribute 'path'

**Comment by benkiel** [comment]
Fixed with #4 and #6
